apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: prod
  annotations:
    ingress.bluemix.net/client-max-body-size: 512m
    ingress.bluemix.net/redirect-to-https: "true"
    ingress.bluemix.net/rewrite-path: |
      serviceName=marmotta rewrite=/;
      serviceName=identity-service rewrite=/;
      serviceName=frontend-service rewrite=/;
      serviceName=catalogue-service rewrite=/;
      serviceName=business-process-service rewrite=/;
      serviceName=keycloak rewrite=/nimble.eu-de.containers.appdomain.cloud/;
      serviceName=registration-service rewrite=/;
      serviceName=csb-kafka rewrite=/;
      serviceName=messaging-service rewrite=/;
      serviceName=hwm rewrite=/;
      serviceName=grafana-grafana rewrite=/;
      serviceName=dashboards-service rewrite=/;
      serviceName=object-store rewrite=/;
      serviceName=data-channels rewrite=/;
      serviceName=data-pipes rewrite=/;
      serviceName=collaboration-service rewrite=/;
      serviceName=eureka-service rewrite=/;
  name: rules-prod
spec:
  tls:
  - hosts:
    - nimble.eu-de.containers.appdomain.cloud
    secretName: nimble
  rules:
  - host: nimble.eu-de.containers.appdomain.cloud
    http:
      paths:
        - path: /identity/
          backend:
            serviceName: identity-service
            servicePort: 9096
        - path: /frontend/
          backend:
            serviceName: frontend-service
            servicePort: 8080
        - path: /catalogue/
          backend:
            serviceName: catalogue-service
            servicePort: 8095
        - path: /business-process/
          backend:
            serviceName: business-process-service
            servicePort: 8085
        - path: /marmotta/
          backend:
            serviceName: marmotta
            servicePort: 8080
        - path: /keycloak/
          backend:
            serviceName: keycloak
            servicePort: 8080
        - path: /register/
          backend:
            serviceName: registration-service
            servicePort: 8080     
        - path: /csb/
          backend:
            serviceName: csb-kafka
            servicePort: 8080
        - path: /messaging/
          backend:
            serviceName: messaging-service
            servicePort: 8080
        - path: /HWServlet
          backend:
            serviceName: hwm
            servicePort: 8080
        - path: /dashboards/
          backend:
            serviceName: dashboards-service
            servicePort: 8080
        - path: /grafana/
          backend:
            serviceName: grafana-grafana
            servicePort: 80
        - path: /object-store/
          backend:
            serviceName: object-store
            servicePort: 8080
        - path: /channels/
          backend:
            serviceName: data-channels
            servicePort: 8080
        - path: /pipes/
          backend:
            serviceName: data-pipes
            servicePort: 8080            
        - path: /collaborations/
          backend:
            serviceName: collaboration-service
            servicePort: 8080
        - path: /eureka/
          backend:
            serviceName: eureka-service
            servicePort: 8080
