kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  # "namespace" omitted since ClusterRoles are not namespaced
  name: secret-reader
  namespace: default  
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "watch", "list"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: read-secrets
  namespace: default # This only grants permissions within the "default" namespace.
subjects:
- kind: ServiceAccount
  name: jenkins-slave-sa
  namespace: build
roleRef:
  kind: Role
  name: secret-reader
  apiGroup: rbac.authorization.k8s.io