apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: jenkins-master
    release: "2.121.2"
    component: nimble-jenkins-master
  name: nimble-jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      component: nimble-jenkins-master
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  revisionHistoryLimit: 5
  template:
    metadata:
      labels:
        app: jenkins-master
        release: "2.121.2"
        component: nimble-jenkins-master
    spec:
      containers:
      - image: jenkins/jenkins:2.121.2
        imagePullPolicy: Always
        name: nimble-jenkins
        env:
          - name: JENKINS_OPTS
            value: "--prefix=/jenkins"
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 50000
          name: slavelistener
          protocol: TCP
        resources:
          requests:
            cpu: 200m
            memory: 1024Mi
        volumeMounts:
        - mountPath: /var/jenkins_home
          name: jenkins-home
      restartPolicy: Always
      volumes:
      - name: jenkins-home
        persistentVolumeClaim:
          claimName: jenkins-data
